/**
 * Clio Drive HTML Generator
 *
 * Generates a lightweight redirect/landing page for a finalised assessment.
 * Saved to Clio Drive so users can jump straight to the Hub from within Clio.
 *
 * Clio's document viewer sandboxes HTML (blocks meta refresh and JS),
 * so this page shows a minimal summary with a prominent link to the Hub.
 */

interface AssessmentHtmlParams {
  assessmentId: string;
  assessmentReference: string;
  clientName: string;
  matterReference: string;
  riskLevel: string;
  score: number;
  finalisedAt: string;
  hubBaseUrl: string;
}

const RISK_COLOURS: Record<string, { bg: string; text: string }> = {
  LOW: { bg: '#d4edda', text: '#155724' },
  MEDIUM: { bg: '#fff3cd', text: '#856404' },
  HIGH: { bg: '#f8d7da', text: '#721c24' },
};

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDate(isoDate: string): string {
  return new Date(isoDate).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Generate a lightweight HTML landing page for a finalised assessment.
 * Shows key details (client, risk level, refs) and a prominent link to the Hub.
 * Clio's viewer blocks auto-redirect, so the link must be clicked manually.
 */
export function generateAssessmentHtml(params: AssessmentHtmlParams): string {
  const {
    assessmentId,
    assessmentReference,
    clientName,
    matterReference,
    riskLevel,
    score,
    finalisedAt,
    hubBaseUrl,
  } = params;

  const riskColour = RISK_COLOURS[riskLevel] || RISK_COLOURS.MEDIUM;
  const hubUrl = `${hubBaseUrl}/assessments/${assessmentId}`;
  const generatedAt = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="refresh" content="0;url=${escapeHtml(hubUrl)}">
  <title>AML Risk Assessment - ${escapeHtml(clientName)} (${escapeHtml(assessmentReference)})</title>
  <script>try{window.top.location.href="${escapeHtml(hubUrl)}";}catch(e){window.location.href="${escapeHtml(hubUrl)}";}</script>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f5f5;">
  <div style="max-width:480px;margin:48px auto;background:#fff;border-radius:12px;box-shadow:0 2px 12px rgba(0,0,0,0.1);overflow:hidden;text-align:center;">

    <!-- Header -->
    <div style="padding:24px 32px;background:#1a1a2e;color:#fff;">
      <h1 style="margin:0 0 4px;font-size:18px;font-weight:600;">AML Risk Assessment</h1>
      <p style="margin:0;font-size:14px;opacity:0.85;">${escapeHtml(clientName)}</p>
    </div>

    <!-- Risk Level Badge -->
    <div style="padding:24px 32px;">
      <div style="display:inline-block;padding:10px 28px;border-radius:8px;background:${riskColour.bg};color:${riskColour.text};font-size:16px;font-weight:700;">
        ${escapeHtml(riskLevel)} RISK
      </div>
      <p style="margin:6px 0 0;font-size:13px;color:#666;">Score: ${score}</p>
    </div>

    <!-- Key Details -->
    <div style="padding:0 32px 20px;font-size:13px;color:#555;">
      <div>${escapeHtml(assessmentReference)} &middot; ${escapeHtml(matterReference)}</div>
      <div style="margin-top:4px;">Finalised ${formatDate(finalisedAt)}</div>
    </div>

    <!-- Prominent Link -->
    <div style="padding:0 32px 28px;">
      <a href="${escapeHtml(hubUrl)}" target="_blank" rel="noopener noreferrer"
         style="display:inline-block;padding:14px 40px;background:#1a1a2e;color:#fff;text-decoration:none;border-radius:8px;font-size:15px;font-weight:600;">
        Open in Eventus Hub
      </a>
      <p style="margin:10px 0 0;font-size:12px;color:#999;">
        View the full CDD checklist, evidence, and scoring breakdown.
      </p>
    </div>

    <!-- Footer -->
    <div style="padding:12px 32px;background:#f8f9fa;border-top:1px solid #eee;">
      <p style="margin:0;font-size:11px;color:#999;">
        Generated by Eventus AML Compliance Hub on ${generatedAt}
      </p>
    </div>

  </div>
</body>
</html>`;
}
