/**
 * File Note HTML renderer for Clio Drive.
 *
 * Renders a CDD-checklist file note as a self-contained HTML document,
 * matching the SoW/SoF and Companies House layout so the Compliance folder
 * reads as a coherent set.
 */

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDate(isoDate: string): string {
  return new Date(isoDate).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export interface FileNoteHtmlParams {
  /** Surrounding assessment context. */
  clientName: string;
  matterReference: string;
  assessmentReference: string;
  /** Displayed checklist item number (1, 2, 3…) — null when this note isn't tied to a specific item. */
  itemNumber: number | null;
  /** Human-readable requirement text (the checklist item's displayText or description). */
  itemLabel: string | null;
  /** Note body the user typed. */
  notes: string;
  /** Author display name, if available. */
  authorName: string | null;
  /** When the note was created. */
  createdAt: string;
}

export function generateFileNoteHtml(params: FileNoteHtmlParams): string {
  const {
    clientName,
    matterReference,
    assessmentReference,
    itemNumber,
    itemLabel,
    notes,
    authorName,
    createdAt,
  } = params;

  const heading = itemNumber !== null
    ? `File note — Item ${itemNumber}`
    : 'File note';

  // Preserve line breaks in the note body but escape everything for safety.
  const escapedNoteBody = escapeHtml(notes).replace(/\r?\n/g, '<br>');

  const generatedAt = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(heading)} - ${escapeHtml(clientName)} (${escapeHtml(assessmentReference)})</title>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f5f5;">
  <div style="max-width:680px;margin:32px auto;background:#fff;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1);overflow:hidden;">

    <!-- Header -->
    <div style="padding:24px 32px;background:#1a1a2e;color:#fff;">
      <h1 style="margin:0 0 4px;font-size:20px;font-weight:600;">${escapeHtml(heading)}</h1>
      <p style="margin:0;font-size:14px;opacity:0.85;">${escapeHtml(clientName)}</p>
    </div>

    <!-- Assessment context -->
    <div style="padding:20px 32px;border-bottom:1px solid #eee;">
      <table style="width:100%;font-size:13px;color:#444;border-collapse:collapse;">
        <tr><td style="padding:4px 0;font-weight:600;width:160px;">Client</td><td style="padding:4px 0;">${escapeHtml(clientName)}</td></tr>
        <tr><td style="padding:4px 0;font-weight:600;">Assessment Ref</td><td style="padding:4px 0;">${escapeHtml(assessmentReference)}</td></tr>
        <tr><td style="padding:4px 0;font-weight:600;">Matter Ref</td><td style="padding:4px 0;">${escapeHtml(matterReference)}</td></tr>
        <tr><td style="padding:4px 0;font-weight:600;">Recorded</td><td style="padding:4px 0;">${formatDate(createdAt)}</td></tr>
        ${authorName ? `<tr><td style="padding:4px 0;font-weight:600;">Author</td><td style="padding:4px 0;">${escapeHtml(authorName)}</td></tr>` : ''}
      </table>
    </div>

    ${itemLabel
      ? `<div style="padding:16px 32px;border-bottom:1px solid #eee;background:#f8f9fa;">
      <p style="margin:0 0 4px;font-size:11px;font-weight:600;color:#666;text-transform:uppercase;letter-spacing:0.5px;">Checklist item${itemNumber !== null ? ` ${itemNumber}` : ''}</p>
      <p style="margin:0;font-size:13px;color:#333;">${escapeHtml(itemLabel)}</p>
    </div>`
      : ''}

    <!-- Note body -->
    <div style="padding:20px 32px;">
      <h2 style="margin:0 0 12px;font-size:16px;color:#1a1a2e;">Note</h2>
      <div style="font-size:14px;color:#222;line-height:1.55;white-space:normal;">${escapedNoteBody}</div>
    </div>

    <!-- Footer -->
    <div style="padding:16px 32px;background:#f8f9fa;border-top:1px solid #eee;text-align:center;">
      <p style="margin:0;font-size:11px;color:#999;">
        Generated by Eventus AML Compliance Hub on ${escapeHtml(generatedAt)}.
      </p>
    </div>

  </div>
</body>
</html>`;
}
