import { describe, it, expect } from 'vitest';
import { generateAssessmentHtml } from '../drive-html';

const BASE_PARAMS = {
  assessmentId: 'test-uuid-123',
  assessmentReference: 'A-00001-2026',
  clientName: 'Acme Ltd',
  matterReference: 'M-00001-2026',
  riskLevel: 'MEDIUM',
  score: 6,
  finalisedAt: '2026-03-07T14:30:00.000Z',
  hubBaseUrl: 'https://eventus-aml-hub.vercel.app',
};

describe('generateAssessmentHtml', () => {
  it('generates valid HTML with DOCTYPE', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toMatch(/^<!DOCTYPE html>/);
    expect(html).toContain('</html>');
  });

  it('includes the client name in the title and header', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('<title>AML Risk Assessment - Acme Ltd (A-00001-2026)</title>');
    expect(html).toContain('Acme Ltd');
  });

  it('displays the risk level with correct styling', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('MEDIUM RISK');
    expect(html).toContain('Score: 6');
  });

  it('displays LOW risk with green styling', () => {
    const html = generateAssessmentHtml({ ...BASE_PARAMS, riskLevel: 'LOW', score: 2 });
    expect(html).toContain('LOW RISK');
    expect(html).toContain('#d4edda'); // green background
  });

  it('displays HIGH risk with red styling', () => {
    const html = generateAssessmentHtml({ ...BASE_PARAMS, riskLevel: 'HIGH', score: 12 });
    expect(html).toContain('HIGH RISK');
    expect(html).toContain('#f8d7da'); // red background
  });

  it('includes assessment and matter references', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('A-00001-2026');
    expect(html).toContain('M-00001-2026');
  });

  it('includes a link to the Hub assessment page', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('https://eventus-aml-hub.vercel.app/assessments/test-uuid-123');
    expect(html).toContain('Open in Eventus Hub');
  });

  it('includes meta refresh redirect to Hub', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('meta http-equiv="refresh"');
    expect(html).toContain('url=https://eventus-aml-hub.vercel.app/assessments/test-uuid-123');
  });

  it('includes JavaScript redirect to Hub', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('window.top.location.href=');
    expect(html).toContain('https://eventus-aml-hub.vercel.app/assessments/test-uuid-123');
  });

  it('includes the generated-by footer', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('Generated by Eventus AML Compliance Hub');
  });

  it('escapes HTML characters in client name', () => {
    const html = generateAssessmentHtml({
      ...BASE_PARAMS,
      clientName: 'Smith & Jones <Partners>',
    });
    expect(html).toContain('Smith &amp; Jones &lt;Partners&gt;');
    expect(html).not.toContain('Smith & Jones <Partners>');
  });

  it('includes formatted finalised date', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('Finalised');
    expect(html).toContain('7 March 2026');
  });

  it('shows CDD checklist description text', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('View the full CDD checklist, evidence, and scoring breakdown.');
  });
});
