import { describe, it, expect } from 'vitest';
import { generateAssessmentHtml } from '../drive-html';

const BASE_PARAMS = {
  assessmentId: 'test-uuid-123',
  assessmentReference: 'A-00001-2026',
  clientName: 'Acme Ltd',
  matterReference: 'M-00001-2026',
  riskLevel: 'MEDIUM',
  score: 6,
  finalisedAt: '2026-03-07T14:30:00.000Z',
  mandatoryActions: [
    { description: 'Verify identity of instructing director', category: 'cdd' },
    { description: 'Obtain company documents', category: 'cdd' },
    { description: 'Source of Wealth form', category: 'sow' },
  ],
  hubBaseUrl: 'https://eventus-aml-hub.vercel.app',
};

describe('generateAssessmentHtml', () => {
  it('generates valid HTML with DOCTYPE', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toMatch(/^<!DOCTYPE html>/);
    expect(html).toContain('</html>');
  });

  it('includes the client name in the title and header', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('<title>AML Risk Assessment - Acme Ltd (A-00001-2026)</title>');
    expect(html).toContain('Acme Ltd');
  });

  it('displays the risk level with correct styling', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('MEDIUM RISK');
    expect(html).toContain('Score: 6');
  });

  it('displays LOW risk with green styling', () => {
    const html = generateAssessmentHtml({ ...BASE_PARAMS, riskLevel: 'LOW', score: 2 });
    expect(html).toContain('LOW RISK');
    expect(html).toContain('#d4edda'); // green background
  });

  it('displays HIGH risk with red styling', () => {
    const html = generateAssessmentHtml({ ...BASE_PARAMS, riskLevel: 'HIGH', score: 12 });
    expect(html).toContain('HIGH RISK');
    expect(html).toContain('#f8d7da'); // red background
  });

  it('includes assessment and matter references', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('A-00001-2026');
    expect(html).toContain('M-00001-2026');
  });

  it('includes a link back to the Hub assessment', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('https://eventus-aml-hub.vercel.app/assessments/test-uuid-123');
    expect(html).toContain('View Full Assessment in Eventus Hub');
  });

  it('groups CDD requirements by category', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('Customer Due Diligence');
    expect(html).toContain('Verify identity of instructing director');
    expect(html).toContain('Obtain company documents');
    expect(html).toContain('Source of Wealth');
    expect(html).toContain('Source of Wealth form');
  });

  it('includes EDD triggers when present', () => {
    const html = generateAssessmentHtml({
      ...BASE_PARAMS,
      eddTriggers: [
        { description: 'Third party funder involved' },
        { description: 'Cross-border transaction' },
      ],
    });
    expect(html).toContain('EDD Triggers');
    expect(html).toContain('Third party funder involved');
    expect(html).toContain('Cross-border transaction');
  });

  it('omits EDD section when no triggers present', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).not.toContain('EDD Triggers');
  });

  it('omits EDD section when triggers is empty array', () => {
    const html = generateAssessmentHtml({ ...BASE_PARAMS, eddTriggers: [] });
    expect(html).not.toContain('EDD Triggers');
  });

  it('includes the generated-by footer', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).toContain('Generated by Eventus AML Compliance Hub');
  });

  it('escapes HTML characters in client name', () => {
    const html = generateAssessmentHtml({
      ...BASE_PARAMS,
      clientName: 'Smith & Jones <Partners>',
    });
    expect(html).toContain('Smith &amp; Jones &lt;Partners&gt;');
    expect(html).not.toContain('Smith & Jones <Partners>');
  });

  it('handles empty mandatory actions', () => {
    const html = generateAssessmentHtml({ ...BASE_PARAMS, mandatoryActions: [] });
    expect(html).toContain('Compliance Requirements');
    // Should still be valid HTML
    expect(html).toContain('</html>');
  });

  it('includes Clio document links when provided', () => {
    const html = generateAssessmentHtml({
      ...BASE_PARAMS,
      clioDocuments: [
        { label: 'Articles of Association', url: 'https://app.clio.com/nc/#/documents/100' },
        { label: 'SoW-Declaration-A-00001-2026.html', url: 'https://app.clio.com/nc/#/documents/101' },
      ],
    });
    expect(html).toContain('Compliance Documents in Clio');
    expect(html).toContain('Articles of Association');
    expect(html).toContain('https://app.clio.com/nc/#/documents/100');
    expect(html).toContain('SoW-Declaration-A-00001-2026.html');
  });

  it('omits document links section when no documents provided', () => {
    const html = generateAssessmentHtml(BASE_PARAMS);
    expect(html).not.toContain('Compliance Documents in Clio');
  });

  it('omits document links section when empty array provided', () => {
    const html = generateAssessmentHtml({ ...BASE_PARAMS, clioDocuments: [] });
    expect(html).not.toContain('Compliance Documents in Clio');
  });
});
