import { describe, it, expect } from 'vitest';
import { generateSowHtml, generateSofHtml } from '../sow-sof-html';

const BASE_SOW_PARAMS = {
  clientName: 'Acme Ltd',
  matterReference: 'M-00001-2026',
  assessmentReference: 'A-00001-2026',
  submittedAt: '2026-03-07T14:30:00.000Z',
};

describe('generateSowHtml', () => {
  it('generates valid HTML with DOCTYPE for individual SoW', () => {
    const html = generateSowHtml({
      ...BASE_SOW_PARAMS,
      formType: 'individual',
      formData: {
        sow_ind_2: ['Employment income or salary', 'Savings accumulated over time'],
        sow_ind_3: 'Director at tech company for 15 years',
        sow_ind_4: '£250,000 – £1,000,000',
        sow_ind_5: '5–10 years',
      },
    });
    expect(html).toMatch(/^<!DOCTYPE html>/);
    expect(html).toContain('</html>');
    expect(html).toContain('Source of Wealth Declaration');
  });

  it('includes client name and references', () => {
    const html = generateSowHtml({
      ...BASE_SOW_PARAMS,
      formType: 'individual',
      formData: { sow_ind_3: 'Test' },
    });
    expect(html).toContain('Acme Ltd');
    expect(html).toContain('M-00001-2026');
    expect(html).toContain('A-00001-2026');
  });

  it('renders individual form fields', () => {
    const html = generateSowHtml({
      ...BASE_SOW_PARAMS,
      formType: 'individual',
      formData: {
        sow_ind_2: ['Employment income or salary'],
        sow_ind_3: 'Salary from BigCo',
        sow_ind_4: 'Under £50,000',
        sow_ind_5: 'Less than 1 year',
      },
    });
    expect(html).toContain('Declared source(s) of wealth');
    expect(html).toContain('Employment income or salary');
    expect(html).toContain('Salary from BigCo');
    expect(html).toContain('Estimated total wealth range');
    expect(html).toContain('Under £50,000');
  });

  it('renders corporate form fields', () => {
    const html = generateSowHtml({
      ...BASE_SOW_PARAMS,
      formType: 'corporate',
      formData: {
        sow_corp_2: ['Trading profits from ongoing business'],
        sow_corp_3: 'Software development services',
        sow_corp_4: '5–10 years',
        sow_corp_5: 'Year ended 31 March 2025',
      },
    });
    expect(html).toContain('Corporate / LLP');
    expect(html).toContain('Trading profits from ongoing business');
    expect(html).toContain('How long has the entity been trading');
    expect(html).toContain('Most recent accounts period');
  });

  it('shows "Not provided" for missing fields', () => {
    const html = generateSowHtml({
      ...BASE_SOW_PARAMS,
      formType: 'individual',
      formData: {},
    });
    expect(html).toContain('Not provided');
  });

  it('renders checkbox values as a list', () => {
    const html = generateSowHtml({
      ...BASE_SOW_PARAMS,
      formType: 'individual',
      formData: {
        sow_ind_2: ['Employment income or salary', 'Inheritance', 'Gift'],
      },
    });
    expect(html).toContain('<li');
    expect(html).toContain('Employment income or salary');
    expect(html).toContain('Inheritance');
    expect(html).toContain('Gift');
  });

  it('escapes HTML in form values', () => {
    const html = generateSowHtml({
      ...BASE_SOW_PARAMS,
      clientName: 'Smith & Jones <Partners>',
      formType: 'individual',
      formData: {
        sow_ind_3: 'Income from <script>alert("xss")</script>',
      },
    });
    expect(html).toContain('Smith &amp; Jones &lt;Partners&gt;');
    expect(html).toContain('&lt;script&gt;');
    expect(html).not.toContain('<script>');
  });

  it('includes the generation footer', () => {
    const html = generateSowHtml({
      ...BASE_SOW_PARAMS,
      formType: 'individual',
      formData: {},
    });
    expect(html).toContain('Generated by Eventus AML Compliance Hub');
  });
});

describe('generateSofHtml', () => {
  it('generates valid HTML with all SoF fields', () => {
    const html = generateSofHtml({
      ...BASE_SOW_PARAMS,
      formData: {
        sof_2: 'Client (self-funded)',
        sof_3: 'Personal savings',
        sof_4: 'HSBC',
        sof_5: 'Jane Smith',
        sof_6: '£350,000 expected within 14 days',
      },
    });
    expect(html).toMatch(/^<!DOCTYPE html>/);
    expect(html).toContain('Source of Funds Declaration');
    expect(html).toContain('Who is providing the funds');
    expect(html).toContain('Client (self-funded)');
    expect(html).toContain('Personal savings');
    expect(html).toContain('HSBC');
    expect(html).toContain('Jane Smith');
    expect(html).toContain('£350,000 expected within 14 days');
  });

  it('includes client name and references', () => {
    const html = generateSofHtml({
      ...BASE_SOW_PARAMS,
      formData: {},
    });
    expect(html).toContain('Acme Ltd');
    expect(html).toContain('A-00001-2026');
    expect(html).toContain('M-00001-2026');
  });

  it('shows "Not provided" for empty form data', () => {
    const html = generateSofHtml({
      ...BASE_SOW_PARAMS,
      formData: {},
    });
    // All 5 SoF fields should show "Not provided"
    const matches = html.match(/Not provided/g);
    expect(matches).toBeTruthy();
    expect(matches!.length).toBe(5);
  });
});
